In [1]:
import tensorflow as tf
print('TensorFlow version: ', tf.__version__)

TensorFlow version:  2.19.0


In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [20]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])


In [21]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.57998675,  0.3654912 ,  0.10751919, -0.20016158,  0.23917681,
        -0.00937681, -0.41066134, -0.07412811,  0.21955457,  0.21439327]],
      dtype=float32)

In [22]:
tf.nn.softmax(predictions).numpy()

array([[0.0545159 , 0.14032629, 0.10841846, 0.07970382, 0.12367485,
        0.09645749, 0.06457438, 0.09040965, 0.12127173, 0.12064742]],
      dtype=float32)

In [23]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [24]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.338653)

In [25]:
model.compile(optimizer='adam',
             loss = loss_fn,
             metrics= ['accuracy'])

In [26]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 552us/step - accuracy: 0.8545 - loss: 0.4929
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 531us/step - accuracy: 0.9560 - loss: 0.1508
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 533us/step - accuracy: 0.9681 - loss: 0.1082
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 531us/step - accuracy: 0.9731 - loss: 0.0863
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 517us/step - accuracy: 0.9758 - loss: 0.0770


In [10]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - 389us/step - accuracy: 0.9242 - loss: 0.2707


[0.2706740200519562, 0.9241999983787537]

In [11]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.39389795e-06, 3.21701670e-08, 7.75461522e-05, 5.62622305e-03,
        4.91587770e-10, 1.64816374e-04, 3.40107699e-11, 9.92346168e-01,
        6.41331892e-04, 1.14252267e-03],
       [2.66089751e-06, 6.20624007e-07, 9.83563781e-01, 1.32126845e-02,
        8.93252740e-15, 1.78991340e-03, 7.78165340e-05, 4.85085409e-12,
        1.35245686e-03, 4.74487151e-11],
       [7.77626883e-06, 9.68536377e-01, 2.68249400e-03, 2.41614622e-03,
        1.40629854e-04, 7.89606886e-04, 1.56171084e-03, 5.17053436e-03,
        1.80102214e-02, 6.84464700e-04],
       [9.96818006e-01, 1.67248264e-11, 3.78251971e-05, 2.12309897e-05,
        4.05064843e-10, 3.05371336e-03, 5.82279370e-07, 1.24596468e-07,
        6.70294030e-05, 1.58539194e-06],
       [9.74595780e-04, 2.27712030e-06, 1.48095319e-03, 3.16062156e-04,
        9.44483638e-01, 1.03321895e-02, 9.07560624e-03, 7.05856457e-03,
        6.74427999e-03, 1.95318572e-02]], dtype=float32)>