In [4]:
softmax_output = [0.7, 0.1, 0.2]

type(softmax_output)

list

In [8]:
import numpy as np

softmax_output = np.array(softmax_output).reshape(-1,1)
print(softmax_output)
type(softmax_output)

[[0.7]
 [0.1]
 [0.2]]


numpy.ndarray

In [13]:
print(softmax_output * np.eye(softmax_output.shape[0]))

[[0.7 0.  0. ]
 [0.  0.1 0. ]
 [0.  0.  0.2]]


In [14]:
print(np.diagflat(softmax_output))

[[0.7 0.  0. ]
 [0.  0.1 0. ]
 [0.  0.  0.2]]


In [ ]:
y_true = np.