In [4]:
softmax_output = [0.7, 0.1, 0.2]

type(softmax_output)

list

In [8]:
import numpy as np

softmax_output = np.array(softmax_output).reshape(-1,1)
print(softmax_output)
type(softmax_output)

[[0.7]
 [0.1]
 [0.2]]


numpy.ndarray

In [13]:
print(softmax_output * np.eye(softmax_output.shape[0]))

[[0.7 0.  0. ]
 [0.  0.1 0. ]
 [0.  0.  0.2]]


In [14]:
print(np.diagflat(softmax_output))

[[0.7 0.  0. ]
 [0.  0.1 0. ]
 [0.  0.  0.2]]


In [1]:
class Optimizer_SGD:
    
    def __init__(self, learning_rate=1.0):
        self.learning_rate = learning_rate

    def update_params(self, layer):
        layer.weights += -self.learning_rate * layer.dweights
        layer.biases += -self.learning_rate * layer.dbiases

optimizer = Optimizer_SGD()

In [4]:
print(optimizer.learning_rate)

1.0


In [5]:
import random
index = random.randint(0,100)
print(index)

6


In [2]:
URL = 'https://nnfs.io/datasets/fashion_mnist_images.zip' 
FILE = 'fashion_mnist_images.zip' 
FOLDER = 'fashion_mnist_images'

In [3]:
import os 
import urllib 
import urllib.request

if not os.path.isfile(FILE): 
    print(f'Downloading {URL} and saving as {FILE}...') 
    urllib.request.urlretrieve(URL, FILE)

('fashion_mnist_images.zip', <http.client.HTTPMessage at 0x104193a90>)