In [1]:
import numpy as np

In [2]:
z = np.array( [[1, 2, -3, -4],
               [2, -7, -1, 3],
               [-1, 2, 5, -1]])

dvalues = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

drelu = dvalues.copy()
drelu[z <= 0] = 0

print(drelu)

[[ 1  2  0  0]
 [ 5  0  0  8]
 [ 0 10 11  0]]


In [1]:
import numpy as np

dvalues = np.array([[1, 1, 1],
                    [2, 2, 2],
                    [3, 3, 3]])

inputs = np.array([[1, 2, 3, 2.5],
                   [2, 5, -1, 2],
                   [-1.5, 2.7, 3.3, -0.8]])

weights = np.array([[0.2, 0.8, -0.5, 1],
                    [0.5, -0.91, 0.26, -0.5],
                    [-0.26, -0.27, 0.17, 0.87]]).T

biases = np.array([[2, 3, 0.5]])

layer_outputs = np.dot(inputs, weights) + biases
relu_outputs = np.maximum(0, layer_outputs)

drelu = relu_outputs.copy()
drelu[layer_outputs <= 0] = 0

dinputs = np.dot(drelu, weights.T)
dweights = np.dot(inputs.T, drelu)
dbiases = np.sum(drelu, axis = 0, keepdims=True)

weights += -0.001*dweights
biases  += -0.001*biases


In [2]:
a = np.dot(dvalues, inputs) # 3.3 * 3.4
print(a.T)

[[ 1.5  3.   4.5]
 [ 9.7 19.4 29.1]
 [ 5.3 10.6 15.9]
 [ 3.7  7.4 11.1]]


In [4]:
b = np.dot(inputs.T, dvalues)
print(b)

[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


In [5]:
# a = dvalues.T * inputs.T
# b = dvalues   * inputs.T