In [1]:
import numpy as np

In [2]:
z = np.array( [[1, 2, -3, -4],
               [2, -7, -1, 3],
               [-1, 2, 5, -1]])

dvalues = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

drelu = dvalues.copy()
drelu[z <= 0] = 0

print(drelu)

[[ 1  2  0  0]
 [ 5  0  0  8]
 [ 0 10 11  0]]


In [22]:
import numpy as np

dvalues = np.array([[1, 1, 1],
                    [2, 2, 2],
                    [3, 3, 3]])

inputs = np.array([[1, 2, 3, 2.5],
                   [2, 5, -1, 2],
                   [-1.5, 2.7, 3.3, -0.8]])

weights = np.array([[0.2, 0.8, -0.5, 1],
                    [0.5, -0.91, 0.26, -0.5],
                    [-0.26, -0.27, 0.17, 0.87]]).T

biases = np.array([[2, 3, 0.5]])

layer_outputs = np.dot(inputs, weights) + biases
relu_outputs = np.maximum(0, layer_outputs)

drelu = relu_outputs.copy()
drelu[layer_outputs <= 0] = 0

dinputs = np.dot(drelu, weights.T)
dweights = np.dot(inputs.T, drelu)
dbiases = np.sum(drelu, axis = 0, keepdims=True)

weights += -0.001*dweights
biases  += -0.001*biases


In [23]:
print(dinputs )
print(dweights)
print(dbiases)

[[ 0.9449   2.09495 -1.67995  6.26995]
 [ 1.728    7.066   -4.416    9.074  ]
 [ 0.80074  0.16457 -0.42732  0.90712]]
[[20.485  -0.3665  2.746 ]
 [57.907   5.2577  5.8402]
 [10.153   7.0983  7.0408]
 [28.672   2.1842  6.3417]]
[[15.11   2.261  2.611]]


In [24]:
print(weights)

[[ 0.179515   0.5003665 -0.262746 ]
 [ 0.742093  -0.9152577 -0.2758402]
 [-0.510153   0.2529017  0.1629592]
 [ 0.971328  -0.5021842  0.8636583]]


In [25]:
print(biases)

[[1.998  2.997  0.4995]]
