In [1]:
import numpy as np

In [10]:
softmax_outputs = np.array( [[0.7, 0.1, 0.2],
                             [0.1, 0.5, 0.4],
                             [0.02, 0.9, 0.08]])


class_targets = np.array([[1, 0, 0],
                          [0, 1, 0],
                          [0, 1, 0]])



In [16]:
correct_confidences =   np.sum (softmax_outputs * class_targets, axis=1 )
print(correct_confidences)

[0.7 0.5 0.9]


In [18]:
class Loss:
    def calulate(self, output, y):
        sample_losses = self.forward(ouput, y)
        data_loss = np.mean(sample_losses)
        return data_loss

class Loss_CategoricalCrossentropy(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)
        # y_true is like class_targets
        if len(y_true.shape) == 1:
            correct_confidences  = y_pred_clipped[ range(samples), y_true]
        elif len(y_true.shape) == 2:
            correct_confidences  = np.sum (y_pred_clipped * y_true, axis=1 )

        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods

In [27]:
predictions = np.argmax(softmax_outputs, axis=1)
print(predictions)

[0 1 1]


In [32]:
import numpy as np

softmax_outputs = np.array( [[0.7, 0.2, 0.1],
                             [0.5, 0.1, 0.4],
                             [0.02, 0.9, 0.08]])

class_targets = np.array( [0, 1, 1] )

predictions = np.argmax(softmax_outputs, axis=1)

if len(class_targets.shape) == 2:
    class_targets = np.argmax(class_targets, axis=1)

accuracy = np.mean(predictions == class_targets)

print(accuracy)

0.6666666666666666


In [30]:
print(predictions)

[0 0 1]


In [33]:
print(class_targets)

[0 1 1]


In [36]:
accuracy = np.mean(predictions == class_targets)

print(accuracy)

0.6666666666666666
