In [7]:
inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

In [8]:
output = [inputs[0]*weights1[0]+
          inputs[1]*weights1[1]+
          inputs[2]*weights1[2]+
          inputs[3]*weights1[3]+bias1,

          inputs[0]*weights2[0]+
          inputs[1]*weights2[1]+
          inputs[2]*weights2[2]+
          inputs[3]*weights2[3]+bias2,

          inputs[0]*weights3[0]+
          inputs[1]*weights3[1]+
          inputs[2]*weights3[2]+
          inputs[3]*weights3[3]+bias3
         ]
print(output)

[4.8, 1.21, 2.385]


In [9]:
inputs = [1, 2, 3, 2.5]

weights = [ [0.2, 0.8, -0.5, 1],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87] ]

biases = [2, 3, 0.5]

layer_outputs = []

for n_weight, n_bias in zip(weights, biases):
    neuron_out = 0
    for n_input, weight in zip(inputs, n_weight):
        neuron_out += n_input*weight
    neuron_out += n_bias
    layer_outputs.append(neuron_out)

print(layer_outputs)

[4.8, 1.21, 2.385]


In [31]:
import numpy as np
import nnfs

nnfs.init()

n_inputs = 2
n_neurons = 3

weights = 0.01 * np.random.randn(n_inputs, n_neurons)
biases  = np.zeros((1, n_neurons))

print(weights)
print(biases)

[[ 0.01764052  0.00400157  0.00978738]
 [ 0.02240893  0.01867558 -0.00977278]]
[[0. 0. 0.]]


In [35]:
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases  = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        
X, y = spiral_data(samples = 100, classes = 3)

dense1 = Layer_Dense(2, 3)

dense1.forward(X)

print(dense1.output[:2])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]]


In [28]:
print(dense1.weights)

[[-0.01306527  0.01658131 -0.00118164]
 [-0.00680178  0.00666383 -0.0046072 ]]


In [36]:
X.shape

(300, 2)